import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import "./globals.css";

const poppins = Poppins({
subsets: ["latin"],
weight: ['500', '600', '700', '900']

} );

export const metadata: Metadata = {
  title: "Hooke ‣ Gerador de link ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-Br">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
